name: codefly go SDK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: set up
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache: true

      - name: Install Dependencies
        run: go mod tidy && go mod download

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12.2

      - name: generate test generate coverage
        run: go test ./... -coverprofile=cover.out -covermode=atomic -coverpkg=./...

      - name: check test coverage
        id: coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.testcoverage.yaml
          ## when token is not specified (value '') this feature is turend off
          ## in this example badge is created and committed only for main brach
          git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
          ## name of branch where badges are stored
          ## ideally this should be orphan branch (see below how to create this branch)
          git-branch: badges

      - name: test with race detection
        run: go test -race ./... -v
